title: Lemon Career Path
description: Un template de como sería esto
theme: just-the-docs

url: https://rodrivaldivia.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/favicon.ico"

search_enabled: false

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark
